version: '2'
services:
  postgresql:
    image: postgres
    container_name: "gogs-postgresql"
    restart: always
    volumes:
      - "./data/postgresql:/var/lib/postgresql"
    environment:
      - "POSTGRES_USER=gogs"
      - "POSTGRES_PASSWORD=changeme"
      - "POSTGRES_DB=gogs"
    ports:
      - "5432:5432"
  gogs:
    image: gogs/gogs
    container_name: "gogs"
    restart: always
    ports:
      - "10022:22"
      - "10080:3000"
    volumes:
      - "./data/gogs:/data"
      - "./entrypoint.sh:/entrypoint.sh"
    links:
      - postgresql
    entrypoint: "/entrypoint.sh"
  drone-server:
    image: drone/drone:0.8

    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/lib/drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=http://142.93.13.239:8000
      - DRONE_GOGS=true
      - DRONE_GOGS_URL=http://142.93.13.239:10080
      - DRONE_SECRET=ksdf923,msdf9;

  drone-agent:
    image: drone/agent:0.8

    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=ksdf923,msdf9;



# version: '2'
# services:
#     postgres:
#       image: postgres
#       restart: always
#       container_name: "gogs-postgresql"
#       environment:
#        - "POSTGRES_USER=gogs"
#        - "POSTGRES_PASSWORD=changeme"
#        - "POSTGRES_DB=gogs"
#       volumes:
#        - "./data/postgresql:/var/lib/postgresql"
#       networks:
#        - gogs
#     gogs:
#       image: gogs/gogs:latest
#       restart: always
#       container_name: "gogs"
#       ports:
#        - "10022:22"
#        - "10080:3000"
#       links:
#        - postgres
#       environment:
#        - "RUN_CROND=true"
#       networks:
#        - gogs
#       volumes:
#        - "./data/gogs:/data"
#       depends_on:
#        - postgres

# networks:
#     gogs:
#       driver: bridge

# volumes:
#     db-data:
#       driver: local
#     gogs-data:
#       driver: local
